{
  "site": {
    "description": "Games Right Meow is an independent game studio and game development consultancy.",
  },
  "navigation": [
    { "name": "home", "url": "/" },
    { "name": "garden", "url": "/garden" },
    { "name": "games", "url": "/games" },
    { "name": "consulting", "url": "/consulting" },
  ],
}